### ISSUE TITLE
add .pause() function to onEvery()

### ISSUE THREAD

**Issue by frozeman** [serkanyersen/ifvisible.js#10]
stop() already exists, but and pause and resume function would be awesome

**Comment by jabbett** [comment]
Is there an example for how to use `stop()` with `onEvery()`? (I don't use CoffeeScript, so it's hard to understand your annotated source. Thanks!)

**Comment by serkanyersen** [comment]
@frozeman `pause` and `resume` methods are in master. Sorry for all this delay.
@jabbett `onEvery` returns an object containing these methods, here is an example

```javascript
var interval = ifvisible.onEvery(2, function() {
    // operation
});

// to stop this interval
interval.stop();

// to pause
interval.pause();

// to unpause
interval.resume();

// Resume cannot start a stopped interval.
```
Hope this helps

**Comment by frozeman** [comment]
One year delay, but great thanks!! :)
