### ISSUE TITLE
Use UMD and publish to npm

### ISSUE THREAD

**Issue by KyleAMathews** [serkanyersen/ifvisible.js#12]
That'd be great for us Browserify/Webpack users!

This module is exactly what I was looking for so thanks for creating it.

**Comment by serkanyersen** [comment]
c6eb2e0c0e1f75055c42a86ca6ca70058d8c11c2 Adds UMD support. I'll submit to npm when `v1.0.2` is ready

**Comment by dasilvacontin** [comment]
Are you going to publish soon?

**Comment by serkanyersen** [comment]
it's on npm now https://www.npmjs.com/package/ifvisible.js
