### ISSUE TITLE
ifvisible.idle callback being called when user is active

### ISSUE THREAD

**Issue by sfug** [serkanyersen/ifvisible.js#27]
Hi,

I think I found a little glitch in your awesome lib.

Tested in Chrome 46.0.2490.86 m

1) Hit 'http://serkanyersen.github.io/ifvisible.js/demo.html'
2) Open Chrome's console
3) Type 'ifvisible.idle(function() { console.log('idle') });' in the console
4) Let the application sleep by reaching 30s of inactivity
5) Wake up the application by moving the mouse into it. Move the mouse for 30s, without performing any clicks. After 30s of movement, the application will briefly change state to 'idle' and get back to 'active'. That can be verified by the callback registered in step 3, which will be invoked.

**Comment by sfug** [comment]
It seems that when ifvisible transitions from 'idle' to 'active', wakeup() is invoked twice. I thought that would pose no problem as JS is mostly singlethreaded, but it seems that my assumptions are wrong.

**Comment by serkanyersen** [comment]
This issue has been fixed in master now
