### ISSUE TITLE
Android native browser does not trigger any event on device sleep

### ISSUE THREAD

**Issue by dorukeker** [serkanyersen/ifvisible.js#30]
Hello,

Very nice library. Thanks for putting it together.
My use case is for mobile devices. I want the JS fire events up on:
- Browser app close (home button press)
- Open a new tab in the browser
- Device put to sleep (sleep button press)

On iOS Safari and Android Chrome all works well. I receive correct `blur` events for each case.
But on Android native browser (for older devices e.g. Samsung S4 etc.) device sleep does not fire any event.

Any ideas? Suggestions?
Cheers,
Doruk

Ps. In my use case I try to detect these events and kill a socket connection manually. This is why I need the device sleep as well.

**Comment by serkanyersen** [comment]
Hi Doruk,

it's probably way too late for this response but I'll try to answer. ifvisible works on top of browser provided visibility api. As you can [http://caniuse.com/#feat=pagevisibility](see on caniuse.com) browser support is limited in some cases. for older Android browsers it says to use `webkit` prefix and ifvisible already does this.

Plus ifvisible has a polyfill in place for older browsers, but it piggybacks on top of page blur, page focus events and those are only available on desktop browsers I think.

So if it's not working on the native browser it's quite possible that the browser does not trigger these events on device sleep and to my current knowledge there is not much option to get that working.

Sorry :/

**Comment by dorukeker** [comment]
Hi Serkan,
Indeed it was some time ago. No worries :)
Ifvisible.js solved many of the use cases on iOS and Android. For those browsers that does not work properly, I implemented a timer logic.

I used Tock.js for that. So if the user is away for a certain time it triggers an event. And you can build your application logic around this.

Thanks for the library and thanks for the reply.
Cheers,
Doruk
