### ISSUE TITLE
Bug with Angular 2

### ISSUE THREAD

**Issue by aslubsky** [serkanyersen/ifvisible.js#39]
I found a bug in **customEvent** with Angualr 2 RC.6, it replace ifvisible module (type Object) to specified wrapper (type Module) with custom getters and setters, so __ceGUID always are undefined in line
`obj[cgid] = "ifvisible.object.event.identifier" unless obj[cgid]`
I've replaced code to
`var objCgid = obj[cgid] || "ifvisible.object.event.identifier";` in ifvisible.js file local, only for check, works fine.
I've forked this repo but can't build from coffee script. 
Do you plan support this project on coffee or will move to type script ?

**Comment by serkanyersen** [comment]
Hey, sorry for the late response.

Checkout my comment on #38

**Comment by aslubsky** [comment]
Thanks a lot, I've switch to your 2.0.4 version, works fine
