### ISSUE TITLE
ifactive.js?

### ISSUE THREAD

**Issue by brandondrew** [serkanyersen/ifvisible.js#43]
Although ifvisible.js is really cool, and I can definitely see myself using it, If I understand things correctly it actually has nothing to do with visibility, but rather whether the user is moving the mouse over the page, or sending keyboard input to the page.

For example, I can open the [demo](http://serkanyersen.github.io/ifvisible.js/demo.html) in a browser window, keep that the browser window both visible and in front of all other windows, and even click my mouse button on the page, and it still is registered as invisible.

Perhaps a name like "ifactive.js" (or something along those lines) might be better?

**Comment by serkanyersen** [comment]
Ifvisible.js uses the [Page Visibility Api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) underneath and provides a polyfill for it hence the name.

There are some additional tools like idle states and user activity tracking but they are not the main purpose of this library.

Thanks for the suggestion though, hope this clears up the naming choice.
