### ISSUE TITLE
Add off to remove blur/focus events

### ISSUE THREAD

**Issue by frozeman** [serkanyersen/ifvisible.js#8]
For a simple website having only on('blur') etc is useful. But on a large single page app, we need to be able to safely remove events as well.

could you please add .off('blur') etc to your library as well?

**Comment by serkanyersen** [comment]
`off` method is added in adc63b6e3bd7d11911ca66a97b8711fc464f7a27 

use it as `ifvisible.off('blur')` to remove all `blur` or `ifvisible.off('blur', onBlur)` only a specific one.

This needs to be tested. I'll include a test suite soon
